### ISSUE TITLE
What is your performance on DALES?

### ISSUE THREAD

**Issue by jdolbecq** [Arjun-NA/KPConv_for_DALES#1]
Hello, I would like to thank you for sharing this project.

With this code and these training hyper-parameters, did you manage to obtain the performances announced by the DALES research paper (i.e. a mIoU of 0.811) ?

**Comment by Arjun-NA** [comment]
The result of the testing is uploaded [here](https://indiana-my.sharepoint.com/:u:/g/personal/arjuna_iu_edu/ERlV6lBVnQtMvAyfloE354YBSH97WFQx7gkow2xAyLam0Q?e=dfJCV6)
and the [test_accuracy.py](../blob/master/test_accuracy.py) was used to calculate F1 scores which gave [this](../blob/master/Log_2020-09-29_02-19-56/F1_Score.txt) result with  Final Avg micro F1 :  0.97 |  Avg  macro F1:  0.72, which is not upto what they have mentioned (may need some parameter tuning) and as I spoke with them I got to know that they had used only portion of their dataset. But still this result was far better than any other point convolutions I had used.
