### ISSUE TITLE
tf_custom_ops/compile_op.sh Env variable possible error

### ISSUE THREAD

**Issue by MRTBSKTP** [Arjun-NA/KPConv_for_DALES#4]
Hello, thanks for your huge effort i was looking around the repo and found a mismatch concerning files `setup.sh` and `tf_custom_ops/compile_op.sh`. In `setup.sh` local folder tree is configured as `/home/ubuntu/lidar/KPConv_for_DALES/` but `compile_op.sh` declares `TF_LIB2='/home/ubuntu/Arjun/KPConv/tf_custom_ops'` variable. This may cause problems when compiling operations. I am not a huge programming savvy person so i am pointing this for someone more capable/authorized to look at. Again thanks for all the effort i am going to try this repo in the next days.

**Comment by Arjun-NA** [comment]
@MRTBSKTP, Thanks for pointing it out. It has been some time since I used this. Let me know if you have a fix for it. I believe this shouldn't affect you in any way, but please do update if it needs to be modified.
